# Generated by Django 5.2 on 2025-05-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customer_product_capital_expense_sale_salescash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockin',
            name='stock_in_date',
            field=models.DateField(default='2025-05-05'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='markup_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='purchase_price',
            field=models.IntegerField(),
        ),
    ]
