# Generated by Django 5.2 on 2025-05-05 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_stockin_stock_in_date_alter_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockin',
            name='stock_in_date',
        ),
    ]
