# Generated by Django 5.1.6 on 2025-07-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_sale_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact_num',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
