# Generated by Django 5.1.6 on 2025-07-16 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_capitaltransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.product'),
        ),
    ]
