# Generated by Django 5.1.6 on 2025-07-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_expense_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='receipt_path',
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
