# Generated by Django 5.1.6 on 2025-07-16 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_expense_receipt_path_expense_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='stockin',
            name='remaining_quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.sale')),
                ('stockin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.stockin')),
            ],
        ),
    ]
