# Generated by Django 5.1.6 on 2025-07-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_product_stock_stockin_remaining_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salescredit',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
