# Generated by Django 5.1.6 on 2025-07-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_stockin_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockin',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
