# Generated by Django 5.1.6 on 2025-08-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_salescash_created_at_salescredit_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salescash',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='salescredit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
