# Generated by Django 5.1.6 on 2025-08-28 20:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_payable_payablepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitaltransaction',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
