# Generated by Django 5.1.6 on 2025-09-04 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_alter_capitaltransaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='product',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='sale',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='accounts.account'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('account', 'contact_num'), name='uniq_contact_per_account'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('account', 'product_name'), name='uniq_product_name_per_account'),
        ),
    ]
