# Generated by Django 5.1.6 on 2025-09-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_customer_account_product_account_sale_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_medium',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/medium/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_thumb',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/thumbs/'),
        ),
    ]
