# Generated by Django 5.1.6 on 2025-09-05 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_product_image_medium_product_image_thumb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_medium',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_thumb',
        ),
    ]
