# Generated by Django 5.1.6 on 2025-09-10 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_product_accounts_pr_account_bc87ac_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='accounts_pr_account_bc87ac_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='accounts_pr_account_8c4e4f_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockin',
            name='accounts_st_product_258c6d_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockin',
            name='accounts_st_account_b27467_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockin',
            name='accounts_st_account_1ca387_idx',
        ),
    ]
