# Generated by Django 4.2.21 on 2025-09-15 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_remove_product_accounts_pr_account_bc87ac_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='credit_limit',
        ),
    ]
