# Generated by Django 5.1.6 on 2025-05-13 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_product_stock_sale_product_sale_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='account',
        ),
    ]
