# Generated by Django 5.1.6 on 2025-05-19 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_sale_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='middle_name',
        ),
    ]
