# Generated by Django 5.1.6 on 2025-08-20 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_salescash_account_salescredit_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockin',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Inventory Purchase', 'Inventory Purchase'), ('Rent', 'Rent'), ('Utilities', 'Utilities'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
