# Generated by Django 5.1.6 on 2025-08-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_account_first_name_alter_account_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salescash',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salescredit',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
