# Generated by Django 5.1.6 on 2025-08-25 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_salescreditpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitaltransaction',
            name='account',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, related_name='capital_transactions', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='capitaltransaction',
            name='source',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='capitaltransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AddIndex(
            model_name='capitaltransaction',
            index=models.Index(fields=['account', 'date'], name='accounts_ca_account_344a41_idx'),
        ),
        migrations.AddIndex(
            model_name='capitaltransaction',
            index=models.Index(fields=['account', 'transaction_type'], name='accounts_ca_account_4bba19_idx'),
        ),
    ]
