# Generated by Django 5.1.6 on 2025-08-25 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_capitaltransaction_account_capitaltransaction_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salescreditpayment',
            name='account',
        ),
        migrations.RemoveField(
            model_name='salescreditpayment',
            name='customer',
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='uniq_product_name_per_account_ci',
        ),
        migrations.RemoveIndex(
            model_name='capitaltransaction',
            name='accounts_ca_account_344a41_idx',
        ),
        migrations.RemoveIndex(
            model_name='capitaltransaction',
            name='accounts_ca_account_4bba19_idx',
        ),
        migrations.RemoveField(
            model_name='capitaltransaction',
            name='account',
        ),
        migrations.RemoveField(
            model_name='capitaltransaction',
            name='source',
        ),
        migrations.RemoveField(
            model_name='product',
            name='account',
        ),
        migrations.AlterField(
            model_name='capitaltransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='SalesCreditPayment',
        ),
    ]
