# Generated by Django 5.1.6 on 2025-09-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_product_thumbnail'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['account', 'product_name'], name='accounts_pr_account_bc87ac_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['account', 'category'], name='accounts_pr_account_8c4e4f_idx'),
        ),
        migrations.AddIndex(
            model_name='stockin',
            index=models.Index(fields=['product', 'account'], name='accounts_st_product_258c6d_idx'),
        ),
        migrations.AddIndex(
            model_name='stockin',
            index=models.Index(fields=['account', 'created_at'], name='accounts_st_account_b27467_idx'),
        ),
        migrations.AddIndex(
            model_name='stockin',
            index=models.Index(fields=['account', 'remaining_quantity'], name='accounts_st_account_1ca387_idx'),
        ),
    ]
