# Generated by Django 5.1.6 on 2025-10-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_forgotpintoken_account_security_answer_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='security_answer_hash',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='security_question_id',
            field=models.IntegerField(default=0),
        ),
    ]
