# Generated by Django 5.1.6 on 2025-10-15 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_alter_account_security_answer_hash_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Capital',
        ),
    ]
