# Generated by Django 5.1.6 on 2025-10-16 12:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_banktransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('capital_deposit', 'Capital Deposit'), ('transfer_cash_out', 'Transfer - Cash Out'), ('transfer_bank_in', 'Transfer - Bank In')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source', models.CharField(blank=True, choices=[('cash', 'Cash On Hand'), ('bank', 'Cash In Bank'), ('capital', 'Capital')], max_length=16, null=True)),
                ('destination', models.CharField(blank=True, choices=[('cash', 'Cash On Hand'), ('bank', 'Cash In Bank'), ('capital', 'Capital')], max_length=16, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('group_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.account')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
