# Generated by Django 5.1.6 on 2025-10-16 19:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='payable',
            name='asset_category',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='payable',
            name='first_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payable',
            name='has_plan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payable',
            name='is_asset',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payable',
            name='item',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='payable',
            name='next_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payable',
            name='plan_monthly',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='payable',
            name='plan_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payablepayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(default='equipment', max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('date_acquired', models.DateField(default=django.utils.timezone.localdate)),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_assets', to='accounts.account')),
            ],
        ),
    ]
