# Generated by Django 5.1.6 on 2025-10-16 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_payable_asset_category_payable_first_due_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceAssets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_on_hand', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_in_bank', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('accounts_receivable', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('inventory', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fixed_assets', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance_assets', to='accounts.account')),
            ],
            options={
                'verbose_name': 'Balance Sheet - Assets',
                'verbose_name_plural': 'Balance Sheet - Assets',
            },
        ),
    ]
