# Generated by Django 5.1.6 on 2025-10-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_balanceassets'),
    ]

    operations = [
        migrations.AddField(
            model_name='payablepayment',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='payablepayment',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', None), _negated=True), fields=('payable', 'idempotency_key'), name='uq_payable_idempotency'),
        ),
    ]
