# Generated by Django 5.2.7 on 2025-10-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_payablepayment_idempotency_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_fixed_asset',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'cash'), ('bank', 'bank'), ('credit', 'credit')], default='cash', max_length=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
