# Generated by Django 5.2.7 on 2025-10-19 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_expense_is_fixed_asset_expense_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedasset',
            name='date_acquired',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
