# Generated by Django 5.2.7 on 2025-10-19 15:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_alter_fixedasset_date_acquired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='payment_method',
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Inventory Purchase', 'Inventory Purchase'), ('Rent', 'Rent'), ('Utilities', 'Utilities'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='date_acquired',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
